name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: summamove
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'   # ⬅️ gebruik PHP 8.2 in plaats van 8.0
        extensions: mbstring, bcmath, pdo_mysql
        coverage: none

    - name: Create .env file
      run: |
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=local" >> .env
        echo "APP_KEY=base64:df9BAtCXdq1w6wC+8/iTLYx6Zxps5cAJthxm4eVo0Y4=" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_TIMEZONE=UTC" >> .env
        echo "APP_URL=http://localhost/" >> .env
        echo "APP_LOCALE=en" >> .env
        echo "APP_FALLBACK_LOCALE=en" >> .env
        echo "APP_FAKER_LOCALE=en_US" >> .env
        echo "APP_MAINTENANCE_DRIVER=file" >> .env
        echo "APP_MAINTENANCE_STORE=database" >> .env
        echo "BCRYPT_ROUNDS=12" >> .env
        echo "LOG_CHANNEL=stack" >> .env
        echo "LOG_STACK=single" >> .env
        echo "LOG_DEPRECATIONS_CHANNEL=null" >> .env
        echo "LOG_LEVEL=debug" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=summamove" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "SESSION_DRIVER=database" >> .env
        echo "SESSION_LIFETIME=120" >> .env
        echo "SESSION_ENCRYPT=false" >> .env
        echo "SESSION_PATH=/" >> .env
        echo "SESSION_DOMAIN=null" >> .env
        echo "BROADCAST_CONNECTION=log" >> .env
        echo "FILESYSTEM_DISK=local" >> .env
        echo "QUEUE_CONNECTION=database" >> .env
        echo "CACHE_STORE=database" >> .env
        echo "CACHE_PREFIX=" >> .env
        echo "MEMCACHED_HOST=127.0.0.1" >> .env
        echo "REDIS_CLIENT=phpredis" >> .env
        echo "REDIS_HOST=127.0.0.1" >> .env
        echo "REDIS_PASSWORD=null" >> .env
        echo "REDIS_PORT=6379" >> .env
        echo "MAIL_MAILER=log" >> .env
        echo "MAIL_HOST=127.0.0.1" >> .env
        echo "MAIL_PORT=2525" >> .env
        echo "MAIL_USERNAME=null" >> .env
        echo "MAIL_PASSWORD=null" >> .env
        echo "MAIL_ENCRYPTION=null" >> .env
        echo "MAIL_FROM_ADDRESS=\"hello@example.com\"" >> .env
        echo "MAIL_FROM_NAME=\"\${APP_NAME}\"" >> .env
        echo "AWS_ACCESS_KEY_ID=" >> .env
        echo "AWS_SECRET_ACCESS_KEY=" >> .env
        echo "AWS_DEFAULT_REGION=us-east-1" >> .env
        echo "AWS_BUCKET=" >> .env
        echo "AWS_USE_PATH_STYLE_ENDPOINT=false" >> .env
        echo "VITE_APP_NAME=\"\${APP_NAME}\"" >> .env

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --no-interaction

    - name: Generate Laravel key
      run: php artisan key:generate

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h127.0.0.1 --silent; do
          echo "Waiting for MySQL..."
          sleep 3
        done

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test
